### ISSUE TITLE
Generate plots in jpeg

### ISSUE THREAD

**Issue by maikhel** [shuyuzheng/synergyfinder#1]
Hello! I'm using your package for counting some data and I have one change proposition. 

Right now, all plots are generated and saved into **pdf** files. Unfortunately, if I need to paste generated plots into Word documents or other places, it's hard to copy it from pdf.
Therefore, it would be great to have an ability to specify output file format and generate plots as images (in any format like **jpeg, png, tiff**).

I'd appreciate any help, cheers.

**Comment by shuyuzheng** [comment]
@maikhel Thank you very much for the great comments and pull requests. I'll update it on Bioconductor Repos.
