### ISSUE TITLE
Define "Summary Synergy Scores" in Documentation

### ISSUE THREAD

**Issue by cannin** [shuyuzheng/synergyfinder#6]
On this page: https://synergyfinder.fimm.fi/synergy/synfin_docs/#datanal

What is the definition of the "Summary Synergy Scores" in the documentation? Is it at average of ZIP scores? Or a different method or a combination scores from different methods? Is it computed automatically in the R package? Is the value in R, the mean value that appears on the contour plot?

**Comment by TangSoftwareLab** [comment]
Hi Cannin,
Please note that the R package is only synchronized with SynergyFinder+, available at the http://www.synergyfinder.org website, but not the fimm.fi website which harbors SynergyFinder3. For questions that are specific to the fimm.fi website, please ask the authors of SynergyFinder2 &3.
Best,
Jing

**Comment by cannin** [comment]
@TangSoftwareLab thanks for the quick response. Closing this issue.
